CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261004202841_InitialCreate') THEN
    CREATE TABLE "AspNetRoles" (
        "Id" uuid NOT NULL,
        "Name" character varying(256),
        "NormalizedName" character varying(256),
        "ConcurrencyStamp" text,
        CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261004202841_InitialCreate') THEN
    CREATE TABLE "AuditLog" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "TimestampUtc" timestamp with time zone NOT NULL,
        "ActorUserId" uuid,
        "ActorEmail" character varying(256),
        "Action" character varying(100) NOT NULL,
        "EntityType" character varying(50),
        "EntityId" character varying(64),
        "Detail" character varying(1000),
        "IpAddress" character varying(64),
        CONSTRAINT "PK_AuditLog" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261004202841_InitialCreate') THEN
    CREATE TABLE "DataProtectionKeys" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "FriendlyName" text,
        "Xml" text,
        CONSTRAINT "PK_DataProtectionKeys" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261004202841_InitialCreate') THEN
    CREATE TABLE "Disciplines" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(100) NOT NULL,
        "IsActive" boolean NOT NULL,
        CONSTRAINT "PK_Disciplines" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261004202841_InitialCreate') THEN
    CREATE TABLE "InjuryTypes" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(100) NOT NULL,
        "IsActive" boolean NOT NULL,
        CONSTRAINT "PK_InjuryTypes" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261004202841_InitialCreate') THEN
    CREATE TABLE "Kingdoms" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(100) NOT NULL,
        "IsActive" boolean NOT NULL,
        CONSTRAINT "PK_Kingdoms" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261004202841_InitialCreate') THEN
    CREATE TABLE "AspNetRoleClaims" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "RoleId" uuid NOT NULL,
        "ClaimType" text,
        "ClaimValue" text,
        CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261004202841_InitialCreate') THEN
    CREATE TABLE "AspNetUsers" (
        "Id" uuid NOT NULL,
        "DisplayName" character varying(100) NOT NULL,
        "KingdomId" integer,
        "CreatedUtc" timestamp with time zone NOT NULL,
        "IsSuspended" boolean NOT NULL,
        "SuspendedUtc" timestamp with time zone,
        "SuspensionReason" character varying(500),
        "UserName" character varying(256),
        "NormalizedUserName" character varying(256),
        "Email" character varying(256),
        "NormalizedEmail" character varying(256),
        "EmailConfirmed" boolean NOT NULL,
        "PasswordHash" text,
        "SecurityStamp" text,
        "ConcurrencyStamp" text,
        "PhoneNumber" text,
        "PhoneNumberConfirmed" boolean NOT NULL,
        "TwoFactorEnabled" boolean NOT NULL,
        "LockoutEnd" timestamp with time zone,
        "LockoutEnabled" boolean NOT NULL,
        "AccessFailedCount" integer NOT NULL,
        CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AspNetUsers_Kingdoms_KingdomId" FOREIGN KEY ("KingdomId") REFERENCES "Kingdoms" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261004202841_InitialCreate') THEN
    CREATE TABLE "Incidents" (
        "Id" uuid NOT NULL,
        "DisciplineId" integer NOT NULL,
        "InjuryTypeId" integer NOT NULL,
        "Severity" integer NOT NULL,
        "InjuryDate" date NOT NULL,
        "EventName" character varying(200) NOT NULL,
        "EventKingdomId" integer NOT NULL,
        "InjuredKingdomId" integer,
        "MatchKey" character varying(64) NOT NULL,
        "LooseKey" character varying(64) NOT NULL,
        "Status" integer NOT NULL,
        "NeedsReview" boolean NOT NULL,
        "MergedIntoIncidentId" uuid,
        "ReviewerNotes" text,
        "CreatedUtc" timestamp with time zone NOT NULL,
        "UpdatedUtc" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Incidents" PRIMARY KEY ("Id"),
        CONSTRAINT ck_incident_no_self_merge CHECK ("MergedIntoIncidentId" IS NULL OR "MergedIntoIncidentId" <> "Id"),
        CONSTRAINT ck_incident_retired_has_target CHECK (("Status" = 2) = ("MergedIntoIncidentId" IS NOT NULL)),
        CONSTRAINT "FK_Incidents_Disciplines_DisciplineId" FOREIGN KEY ("DisciplineId") REFERENCES "Disciplines" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_Incidents_Incidents_MergedIntoIncidentId" FOREIGN KEY ("MergedIntoIncidentId") REFERENCES "Incidents" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_Incidents_InjuryTypes_InjuryTypeId" FOREIGN KEY ("InjuryTypeId") REFERENCES "InjuryTypes" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_Incidents_Kingdoms_EventKingdomId" FOREIGN KEY ("EventKingdomId") REFERENCES "Kingdoms" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_Incidents_Kingdoms_InjuredKingdomId" FOREIGN KEY ("InjuredKingdomId") REFERENCES "Kingdoms" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261004202841_InitialCreate') THEN
    CREATE TABLE "AspNetUserClaims" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" uuid NOT NULL,
        "ClaimType" text,
        "ClaimValue" text,
        CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261004202841_InitialCreate') THEN
    CREATE TABLE "AspNetUserLogins" (
        "LoginProvider" text NOT NULL,
        "ProviderKey" text NOT NULL,
        "ProviderDisplayName" text,
        "UserId" uuid NOT NULL,
        CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
        CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261004202841_InitialCreate') THEN
    CREATE TABLE "AspNetUserRoles" (
        "UserId" uuid NOT NULL,
        "RoleId" uuid NOT NULL,
        CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
        CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261004202841_InitialCreate') THEN
    CREATE TABLE "AspNetUserTokens" (
        "UserId" uuid NOT NULL,
        "LoginProvider" text NOT NULL,
        "Name" text NOT NULL,
        "Value" text,
        CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
        CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261004202841_InitialCreate') THEN
    CREATE TABLE "Reports" (
        "Id" uuid NOT NULL,
        "IncidentId" uuid NOT NULL,
        "ReporterUserId" uuid,
        "DisciplineId" integer NOT NULL,
        "InjuryTypeId" integer NOT NULL,
        "Severity" integer NOT NULL,
        "InjuryDate" date NOT NULL,
        "EventName" character varying(200) NOT NULL,
        "EventKingdomId" integer NOT NULL,
        "InjuredKingdomId" integer,
        "Narrative" text NOT NULL,
        "SubmissionToken" uuid NOT NULL,
        "MatchKey" character varying(64) NOT NULL,
        "LooseKey" character varying(64) NOT NULL,
        "AutoLinked" boolean NOT NULL,
        "PossibleDuplicate" boolean NOT NULL,
        "SubmittedUtc" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Reports" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Reports_AspNetUsers_ReporterUserId" FOREIGN KEY ("ReporterUserId") REFERENCES "AspNetUsers" ("Id") ON DELETE SET NULL,
        CONSTRAINT "FK_Reports_Disciplines_DisciplineId" FOREIGN KEY ("DisciplineId") REFERENCES "Disciplines" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_Reports_Incidents_IncidentId" FOREIGN KEY ("IncidentId") REFERENCES "Incidents" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_Reports_InjuryTypes_InjuryTypeId" FOREIGN KEY ("InjuryTypeId") REFERENCES "InjuryTypes" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_Reports_Kingdoms_EventKingdomId" FOREIGN KEY ("EventKingdomId") REFERENCES "Kingdoms" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_Reports_Kingdoms_InjuredKingdomId" FOREIGN KEY ("InjuredKingdomId") REFERENCES "Kingdoms" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261004202841_InitialCreate') THEN
    INSERT INTO "Disciplines" ("Id", "IsActive", "Name")
    VALUES (1, TRUE, 'Armored Combat');
    INSERT INTO "Disciplines" ("Id", "IsActive", "Name")
    VALUES (2, TRUE, 'Rapier');
    INSERT INTO "Disciplines" ("Id", "IsActive", "Name")
    VALUES (3, TRUE, 'Equestrian');
    INSERT INTO "Disciplines" ("Id", "IsActive", "Name")
    VALUES (4, TRUE, 'Archery');
    INSERT INTO "Disciplines" ("Id", "IsActive", "Name")
    VALUES (5, TRUE, 'Thrown Weapons');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261004202841_InitialCreate') THEN
    INSERT INTO "InjuryTypes" ("Id", "IsActive", "Name")
    VALUES (1, TRUE, 'Head injury / concussion');
    INSERT INTO "InjuryTypes" ("Id", "IsActive", "Name")
    VALUES (2, TRUE, 'Sprain or strain');
    INSERT INTO "InjuryTypes" ("Id", "IsActive", "Name")
    VALUES (3, TRUE, 'Fracture / broken bone');
    INSERT INTO "InjuryTypes" ("Id", "IsActive", "Name")
    VALUES (4, TRUE, 'Dislocation');
    INSERT INTO "InjuryTypes" ("Id", "IsActive", "Name")
    VALUES (5, TRUE, 'Laceration / puncture');
    INSERT INTO "InjuryTypes" ("Id", "IsActive", "Name")
    VALUES (6, TRUE, 'Contusion / bruise');
    INSERT INTO "InjuryTypes" ("Id", "IsActive", "Name")
    VALUES (7, TRUE, 'Eye injury');
    INSERT INTO "InjuryTypes" ("Id", "IsActive", "Name")
    VALUES (8, TRUE, 'Dental injury');
    INSERT INTO "InjuryTypes" ("Id", "IsActive", "Name")
    VALUES (9, TRUE, 'Neck / back / spine');
    INSERT INTO "InjuryTypes" ("Id", "IsActive", "Name")
    VALUES (10, TRUE, 'Heat or cold illness');
    INSERT INTO "InjuryTypes" ("Id", "IsActive", "Name")
    VALUES (11, TRUE, 'Cardiac / medical event');
    INSERT INTO "InjuryTypes" ("Id", "IsActive", "Name")
    VALUES (12, TRUE, 'Other');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261004202841_InitialCreate') THEN
    INSERT INTO "Kingdoms" ("Id", "IsActive", "Name")
    VALUES (1, TRUE, 'An Tir');
    INSERT INTO "Kingdoms" ("Id", "IsActive", "Name")
    VALUES (2, TRUE, 'Ansteorra');
    INSERT INTO "Kingdoms" ("Id", "IsActive", "Name")
    VALUES (3, TRUE, 'Artemisia');
    INSERT INTO "Kingdoms" ("Id", "IsActive", "Name")
    VALUES (4, TRUE, 'Atenveldt');
    INSERT INTO "Kingdoms" ("Id", "IsActive", "Name")
    VALUES (5, TRUE, 'Atlantia');
    INSERT INTO "Kingdoms" ("Id", "IsActive", "Name")
    VALUES (6, TRUE, 'Avacal');
    INSERT INTO "Kingdoms" ("Id", "IsActive", "Name")
    VALUES (7, TRUE, 'Caid');
    INSERT INTO "Kingdoms" ("Id", "IsActive", "Name")
    VALUES (8, TRUE, 'Calontir');
    INSERT INTO "Kingdoms" ("Id", "IsActive", "Name")
    VALUES (9, TRUE, 'Drachenwald');
    INSERT INTO "Kingdoms" ("Id", "IsActive", "Name")
    VALUES (10, TRUE, 'Ealdormere');
    INSERT INTO "Kingdoms" ("Id", "IsActive", "Name")
    VALUES (11, TRUE, 'East');
    INSERT INTO "Kingdoms" ("Id", "IsActive", "Name")
    VALUES (12, TRUE, 'Gleann Abhann');
    INSERT INTO "Kingdoms" ("Id", "IsActive", "Name")
    VALUES (13, TRUE, 'Lochac');
    INSERT INTO "Kingdoms" ("Id", "IsActive", "Name")
    VALUES (14, TRUE, 'Meridies');
    INSERT INTO "Kingdoms" ("Id", "IsActive", "Name")
    VALUES (15, TRUE, 'Middle');
    INSERT INTO "Kingdoms" ("Id", "IsActive", "Name")
    VALUES (16, TRUE, 'Northshield');
    INSERT INTO "Kingdoms" ("Id", "IsActive", "Name")
    VALUES (17, TRUE, 'Outlands');
    INSERT INTO "Kingdoms" ("Id", "IsActive", "Name")
    VALUES (18, TRUE, 'Æthelmearc');
    INSERT INTO "Kingdoms" ("Id", "IsActive", "Name")
    VALUES (19, TRUE, 'Trimaris');
    INSERT INTO "Kingdoms" ("Id", "IsActive", "Name")
    VALUES (20, TRUE, 'West');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261004202841_InitialCreate') THEN
    CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261004202841_InitialCreate') THEN
    CREATE UNIQUE INDEX "RoleNameIndex" ON "AspNetRoles" ("NormalizedName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261004202841_InitialCreate') THEN
    CREATE INDEX "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261004202841_InitialCreate') THEN
    CREATE INDEX "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261004202841_InitialCreate') THEN
    CREATE INDEX "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261004202841_InitialCreate') THEN
    CREATE INDEX "EmailIndex" ON "AspNetUsers" ("NormalizedEmail");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261004202841_InitialCreate') THEN
    CREATE INDEX "IX_AspNetUsers_KingdomId" ON "AspNetUsers" ("KingdomId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261004202841_InitialCreate') THEN
    CREATE UNIQUE INDEX "UserNameIndex" ON "AspNetUsers" ("NormalizedUserName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261004202841_InitialCreate') THEN
    CREATE INDEX "IX_AuditLog_Action" ON "AuditLog" ("Action");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261004202841_InitialCreate') THEN
    CREATE INDEX "IX_AuditLog_TimestampUtc" ON "AuditLog" ("TimestampUtc");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261004202841_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Disciplines_Name" ON "Disciplines" ("Name");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261004202841_InitialCreate') THEN
    CREATE INDEX "IX_Incidents_DisciplineId" ON "Incidents" ("DisciplineId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261004202841_InitialCreate') THEN
    CREATE INDEX "IX_Incidents_EventKingdomId" ON "Incidents" ("EventKingdomId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261004202841_InitialCreate') THEN
    CREATE INDEX "IX_Incidents_InjuredKingdomId" ON "Incidents" ("InjuredKingdomId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261004202841_InitialCreate') THEN
    CREATE INDEX "IX_Incidents_InjuryTypeId" ON "Incidents" ("InjuryTypeId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261004202841_InitialCreate') THEN
    CREATE INDEX "IX_Incidents_LooseKey" ON "Incidents" ("LooseKey");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261004202841_InitialCreate') THEN
    CREATE INDEX "IX_Incidents_MatchKey" ON "Incidents" ("MatchKey");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261004202841_InitialCreate') THEN
    CREATE INDEX "IX_Incidents_MergedIntoIncidentId" ON "Incidents" ("MergedIntoIncidentId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261004202841_InitialCreate') THEN
    CREATE INDEX "IX_Incidents_Status_InjuryDate" ON "Incidents" ("Status", "InjuryDate");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261004202841_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_InjuryTypes_Name" ON "InjuryTypes" ("Name");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261004202841_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Kingdoms_Name" ON "Kingdoms" ("Name");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261004202841_InitialCreate') THEN
    CREATE INDEX "IX_Reports_DisciplineId" ON "Reports" ("DisciplineId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261004202841_InitialCreate') THEN
    CREATE INDEX "IX_Reports_EventKingdomId" ON "Reports" ("EventKingdomId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261004202841_InitialCreate') THEN
    CREATE INDEX "IX_Reports_IncidentId" ON "Reports" ("IncidentId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261004202841_InitialCreate') THEN
    CREATE INDEX "IX_Reports_InjuredKingdomId" ON "Reports" ("InjuredKingdomId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261004202841_InitialCreate') THEN
    CREATE INDEX "IX_Reports_InjuryTypeId" ON "Reports" ("InjuryTypeId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261004202841_InitialCreate') THEN
    CREATE INDEX "IX_Reports_ReporterUserId_MatchKey" ON "Reports" ("ReporterUserId", "MatchKey");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261004202841_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Reports_SubmissionToken" ON "Reports" ("SubmissionToken");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261004202841_InitialCreate') THEN
    PERFORM setval(
        pg_get_serial_sequence('"Disciplines"', 'Id'),
        GREATEST(
            (SELECT MAX("Id") FROM "Disciplines") + 1,
            nextval(pg_get_serial_sequence('"Disciplines"', 'Id'))),
        false);
    PERFORM setval(
        pg_get_serial_sequence('"InjuryTypes"', 'Id'),
        GREATEST(
            (SELECT MAX("Id") FROM "InjuryTypes") + 1,
            nextval(pg_get_serial_sequence('"InjuryTypes"', 'Id'))),
        false);
    PERFORM setval(
        pg_get_serial_sequence('"Kingdoms"', 'Id'),
        GREATEST(
            (SELECT MAX("Id") FROM "Kingdoms") + 1,
            nextval(pg_get_serial_sequence('"Kingdoms"', 'Id'))),
        false);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261004202841_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20261004202841_InitialCreate', '10.0.12');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261004202854_AuditLogAppendOnly') THEN
    CREATE FUNCTION audit_log_append_only() RETURNS trigger AS $$
    BEGIN
        RAISE EXCEPTION 'AuditLog is append-only';
    END;
    $$ LANGUAGE plpgsql;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261004202854_AuditLogAppendOnly') THEN
    CREATE TRIGGER audit_log_no_update_delete
        BEFORE UPDATE OR DELETE ON "AuditLog"
        FOR EACH ROW EXECUTE FUNCTION audit_log_append_only();
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261004202854_AuditLogAppendOnly') THEN
    CREATE TRIGGER audit_log_no_truncate
        BEFORE TRUNCATE ON "AuditLog"
        FOR EACH STATEMENT EXECUTE FUNCTION audit_log_append_only();
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261004202854_AuditLogAppendOnly') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20261004202854_AuditLogAppendOnly', '10.0.12');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261005005931_ReportNarrativeEdit') THEN
    ALTER TABLE "Reports" ADD "NarrativeEditedUtc" timestamp with time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261005005931_ReportNarrativeEdit') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20261005005931_ReportNarrativeEdit', '10.0.12');
    END IF;
END $EF$;
COMMIT;

