// <auto-generated />
using System;
using InjuryReporting.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InjuryReporting.Web.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261004202854_AuditLogAppendOnly")]
    partial class AuditLogAppendOnly
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InjuryReporting.Web.Data.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSuspended")
                        .HasColumnType("boolean");

                    b.Property<int?>("KingdomId")
                        .HasColumnType("integer");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<DateTime?>("SuspendedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SuspensionReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("KingdomId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("InjuryReporting.Web.Data.AuditLogEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ActorEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Detail")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("EntityId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("EntityType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Action");

                    b.HasIndex("TimestampUtc");

                    b.ToTable("AuditLog");
                });

            modelBuilder.Entity("InjuryReporting.Web.Data.Discipline", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Disciplines");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "Armored Combat"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Name = "Rapier"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            Name = "Equestrian"
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            Name = "Archery"
                        },
                        new
                        {
                            Id = 5,
                            IsActive = true,
                            Name = "Thrown Weapons"
                        });
                });

            modelBuilder.Entity("InjuryReporting.Web.Data.Incident", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DisciplineId")
                        .HasColumnType("integer");

                    b.Property<int>("EventKingdomId")
                        .HasColumnType("integer");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("InjuredKingdomId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("InjuryDate")
                        .HasColumnType("date");

                    b.Property<int>("InjuryTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("LooseKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("MatchKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid?>("MergedIntoIncidentId")
                        .HasColumnType("uuid");

                    b.Property<bool>("NeedsReview")
                        .HasColumnType("boolean");

                    b.Property<string>("ReviewerNotes")
                        .HasColumnType("text");

                    b.Property<int>("Severity")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DisciplineId");

                    b.HasIndex("EventKingdomId");

                    b.HasIndex("InjuredKingdomId");

                    b.HasIndex("InjuryTypeId");

                    b.HasIndex("LooseKey");

                    b.HasIndex("MatchKey");

                    b.HasIndex("MergedIntoIncidentId");

                    b.HasIndex("Status", "InjuryDate");

                    b.ToTable("Incidents", t =>
                        {
                            t.HasCheckConstraint("ck_incident_no_self_merge", "\"MergedIntoIncidentId\" IS NULL OR \"MergedIntoIncidentId\" <> \"Id\"");

                            t.HasCheckConstraint("ck_incident_retired_has_target", "(\"Status\" = 2) = (\"MergedIntoIncidentId\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("InjuryReporting.Web.Data.InjuryReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AutoLinked")
                        .HasColumnType("boolean");

                    b.Property<int>("DisciplineId")
                        .HasColumnType("integer");

                    b.Property<int>("EventKingdomId")
                        .HasColumnType("integer");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("IncidentId")
                        .HasColumnType("uuid");

                    b.Property<int?>("InjuredKingdomId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("InjuryDate")
                        .HasColumnType("date");

                    b.Property<int>("InjuryTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("LooseKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("MatchKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Narrative")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("PossibleDuplicate")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ReporterUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("Severity")
                        .HasColumnType("integer");

                    b.Property<Guid>("SubmissionToken")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("SubmittedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DisciplineId");

                    b.HasIndex("EventKingdomId");

                    b.HasIndex("IncidentId");

                    b.HasIndex("InjuredKingdomId");

                    b.HasIndex("InjuryTypeId");

                    b.HasIndex("SubmissionToken")
                        .IsUnique();

                    b.HasIndex("ReporterUserId", "MatchKey");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("InjuryReporting.Web.Data.InjuryType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("InjuryTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "Head injury / concussion"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Name = "Sprain or strain"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            Name = "Fracture / broken bone"
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            Name = "Dislocation"
                        },
                        new
                        {
                            Id = 5,
                            IsActive = true,
                            Name = "Laceration / puncture"
                        },
                        new
                        {
                            Id = 6,
                            IsActive = true,
                            Name = "Contusion / bruise"
                        },
                        new
                        {
                            Id = 7,
                            IsActive = true,
                            Name = "Eye injury"
                        },
                        new
                        {
                            Id = 8,
                            IsActive = true,
                            Name = "Dental injury"
                        },
                        new
                        {
                            Id = 9,
                            IsActive = true,
                            Name = "Neck / back / spine"
                        },
                        new
                        {
                            Id = 10,
                            IsActive = true,
                            Name = "Heat or cold illness"
                        },
                        new
                        {
                            Id = 11,
                            IsActive = true,
                            Name = "Cardiac / medical event"
                        },
                        new
                        {
                            Id = 12,
                            IsActive = true,
                            Name = "Other"
                        });
                });

            modelBuilder.Entity("InjuryReporting.Web.Data.Kingdom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Kingdoms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "An Tir"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Name = "Ansteorra"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            Name = "Artemisia"
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            Name = "Atenveldt"
                        },
                        new
                        {
                            Id = 5,
                            IsActive = true,
                            Name = "Atlantia"
                        },
                        new
                        {
                            Id = 6,
                            IsActive = true,
                            Name = "Avacal"
                        },
                        new
                        {
                            Id = 7,
                            IsActive = true,
                            Name = "Caid"
                        },
                        new
                        {
                            Id = 8,
                            IsActive = true,
                            Name = "Calontir"
                        },
                        new
                        {
                            Id = 9,
                            IsActive = true,
                            Name = "Drachenwald"
                        },
                        new
                        {
                            Id = 10,
                            IsActive = true,
                            Name = "Ealdormere"
                        },
                        new
                        {
                            Id = 11,
                            IsActive = true,
                            Name = "East"
                        },
                        new
                        {
                            Id = 12,
                            IsActive = true,
                            Name = "Gleann Abhann"
                        },
                        new
                        {
                            Id = 13,
                            IsActive = true,
                            Name = "Lochac"
                        },
                        new
                        {
                            Id = 14,
                            IsActive = true,
                            Name = "Meridies"
                        },
                        new
                        {
                            Id = 15,
                            IsActive = true,
                            Name = "Middle"
                        },
                        new
                        {
                            Id = 16,
                            IsActive = true,
                            Name = "Northshield"
                        },
                        new
                        {
                            Id = 17,
                            IsActive = true,
                            Name = "Outlands"
                        },
                        new
                        {
                            Id = 18,
                            IsActive = true,
                            Name = "Æthelmearc"
                        },
                        new
                        {
                            Id = 19,
                            IsActive = true,
                            Name = "Trimaris"
                        },
                        new
                        {
                            Id = 20,
                            IsActive = true,
                            Name = "West"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text");

                    b.Property<string>("Xml")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DataProtectionKeys");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("InjuryReporting.Web.Data.ApplicationUser", b =>
                {
                    b.HasOne("InjuryReporting.Web.Data.Kingdom", "Kingdom")
                        .WithMany()
                        .HasForeignKey("KingdomId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Kingdom");
                });

            modelBuilder.Entity("InjuryReporting.Web.Data.Incident", b =>
                {
                    b.HasOne("InjuryReporting.Web.Data.Discipline", "Discipline")
                        .WithMany()
                        .HasForeignKey("DisciplineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InjuryReporting.Web.Data.Kingdom", "EventKingdom")
                        .WithMany()
                        .HasForeignKey("EventKingdomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InjuryReporting.Web.Data.Kingdom", "InjuredKingdom")
                        .WithMany()
                        .HasForeignKey("InjuredKingdomId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("InjuryReporting.Web.Data.InjuryType", "InjuryType")
                        .WithMany()
                        .HasForeignKey("InjuryTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InjuryReporting.Web.Data.Incident", "MergedInto")
                        .WithMany()
                        .HasForeignKey("MergedIntoIncidentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Discipline");

                    b.Navigation("EventKingdom");

                    b.Navigation("InjuredKingdom");

                    b.Navigation("InjuryType");

                    b.Navigation("MergedInto");
                });

            modelBuilder.Entity("InjuryReporting.Web.Data.InjuryReport", b =>
                {
                    b.HasOne("InjuryReporting.Web.Data.Discipline", "Discipline")
                        .WithMany()
                        .HasForeignKey("DisciplineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InjuryReporting.Web.Data.Kingdom", "EventKingdom")
                        .WithMany()
                        .HasForeignKey("EventKingdomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InjuryReporting.Web.Data.Incident", "Incident")
                        .WithMany("Reports")
                        .HasForeignKey("IncidentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InjuryReporting.Web.Data.Kingdom", "InjuredKingdom")
                        .WithMany()
                        .HasForeignKey("InjuredKingdomId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("InjuryReporting.Web.Data.InjuryType", "InjuryType")
                        .WithMany()
                        .HasForeignKey("InjuryTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InjuryReporting.Web.Data.ApplicationUser", "Reporter")
                        .WithMany()
                        .HasForeignKey("ReporterUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Discipline");

                    b.Navigation("EventKingdom");

                    b.Navigation("Incident");

                    b.Navigation("InjuredKingdom");

                    b.Navigation("InjuryType");

                    b.Navigation("Reporter");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("InjuryReporting.Web.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("InjuryReporting.Web.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InjuryReporting.Web.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("InjuryReporting.Web.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InjuryReporting.Web.Data.Incident", b =>
                {
                    b.Navigation("Reports");
                });
#pragma warning restore 612, 618
        }
    }
}
